qualification = Qualification.find_or_create_by(name: "Automotive Servicing NC II")

qualification.competencies.basic.find_or_create_by(unit_code: "500311105", unit_title: "Participate in workplace communication")
qualification.competencies.basic.find_or_create_by(unit_code: "500311106", unit_title: "Work in team environment")
qualification.competencies.basic.find_or_create_by(unit_code: "500311107", unit_title: "Practice career professionalism")
qualification.competencies.basic.find_or_create_by(unit_code: "500311108", unit_title: "Practice Occupational Health and Safety Procedures")

qualification.competencies.common.find_or_create_by(unit_code: "ALT723201", unit_title: "Apply appropriate sealant/adhesive")
qualification.competencies.common.find_or_create_by(unit_code: "ALT723202", unit_title: "Move and position vehicle")
qualification.competencies.common.find_or_create_by(unit_code: "ALT311202", unit_title: "Perform mensuration and calculation")
qualification.competencies.common.find_or_create_by(unit_code: "ALT723203", unit_title: "Read, interpret and apply specifications and manuals")
qualification.competencies.common.find_or_create_by(unit_code: "ALT723204", unit_title: "Use and apply lubricants/coolants")
qualification.competencies.common.find_or_create_by(unit_code: "ALT723205", unit_title: "Perform shop maintenance")
qualification.competencies.common.find_or_create_by(unit_code: "ALT311204", unit_title: "Perform job estimates")
qualification.competencies.common.find_or_create_by(unit_code: "ALT311205", unit_title: "Interpret/draw technical drawing")
qualification.competencies.common.find_or_create_by(unit_code: "ALT723206", unit_title: "Practice health, safety and environment procedures")
qualification.competencies.common.find_or_create_by(unit_code: "ALT311207", unit_title: "Inspect technical quality of work")
qualification.competencies.common.find_or_create_by(unit_code: "ALT311208", unit_title: "Maintain quality systems")
qualification.competencies.common.find_or_create_by(unit_code: "ALT311209", unit_title: "Provide work skill instructions")
qualification.competencies.common.find_or_create_by(unit_code: "ALT723210", unit_title: "Identify and select original automotive parts and products")

qualification.competencies.core.find_or_create_by(unit_code: "ALT723303", unit_title: "Service automotive battery")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723304", unit_title: "Service ignition system")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723305", unit_title: "Test and repair wiring/lighting system")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723307", unit_title: "Service Starting System")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723308", unit_title: "Service Charging System")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723309", unit_title: "Service Engine Mechanical System")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723310", unit_title: "Service Clutch System")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723311", unit_title: "Service Differential and Front Axle")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723312", unit_title: "Service Steering System")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723314", unit_title: "Service Brake System")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723315", unit_title: "Service Suspension System")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723316", unit_title: "Perform Underchassis Preventive Maintenance")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723313", unit_title: "Overhaul Manual Transmission")
