qualification = Qualification.find_or_create_by(name: "Automotive Servicing NC I")

qualification.competencies.basic.find_or_create_by(unit_code: "500311101", unit_title: "Received and respond to workplace communication")
qualification.competencies.basic.find_or_create_by(unit_code: "500311102", unit_title: "Work with Others")
qualification.competencies.basic.find_or_create_by(unit_code: "500311103", unit_title: "Demonstrate work values")
qualification.competencies.basic.find_or_create_by(unit_code: "500311104", unit_title: "Practice basic housekeeping procedures")

qualification.competencies.common.find_or_create_by(unit_code: "ALT723201", unit_title: "Apply appropriate sealant/adhesive")
qualification.competencies.common.find_or_create_by(unit_code: "ALT723202", unit_title: "Move and position vehicle")
qualification.competencies.common.find_or_create_by(unit_code: "ALT311202", unit_title: "Perform mensuration and calculation")
qualification.competencies.common.find_or_create_by(unit_code: "ALT723203", unit_title: "Read, interpret and apply specifications and manuals")
qualification.competencies.common.find_or_create_by(unit_code: "ALT723204", unit_title: "Use and apply lubricants/coolants")
qualification.competencies.common.find_or_create_by(unit_code: "ALT723205", unit_title: "Perform shop maintenance")
qualification.competencies.common.find_or_create_by(unit_code: "ALT311204", unit_title: "Perform job estimates")
qualification.competencies.common.find_or_create_by(unit_code: "ALT311205", unit_title: "Interpret/draw technical drawing")
qualification.competencies.common.find_or_create_by(unit_code: "ALT723206", unit_title: "Practice health, safety and environment procedures")
qualification.competencies.common.find_or_create_by(unit_code: "ALT311207", unit_title: "Inspect technical quality of work")
qualification.competencies.common.find_or_create_by(unit_code: "ALT311208", unit_title: "Maintain quality systems")
qualification.competencies.common.find_or_create_by(unit_code: "ALT311209", unit_title: "Provide work skill instructions")
qualification.competencies.common.find_or_create_by(unit_code: "ALT723210", unit_title: "Identify and select original automotive parts and products")

qualification.competencies.core.find_or_create_by(unit_code: "ALT723301", unit_title: "Perform diesel engine tune up")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723302", unit_title: "Perform diesel engine tune up")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723354", unit_title: "Remove and replace electrical/electronic units/assemblies")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723355", unit_title: "Remove and tag engine system components")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723356", unit_title: "Remove and tag automotive steering, suspension and brake system components")
qualification.competencies.core.find_or_create_by(unit_code: "ALT723357", unit_title: "Remove and tag transmission system components")